# -*-Python-*-
Import('env')
env = env.Clone()
env.Append(CPPPATH='.')

env.Program('ocl_info',
            ['ocl_info.cc'])
env.Program('ocl_test',
            ['ocl_test.cc'])
env.Command('kernel.h', 'kernel.c',
            'xxd -i <$SOURCE >$TARGET')

